# fly.toml app configuration file generated for simple-messenger on 2025-06-23T12:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "simple-messenger"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[env]
  PORT = "8000"
  ACCESS_KEY = "45000"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"
