services:
  - type: web
    name: simple-messenger
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /
    envVars:
      - key: CORS_ORIGINS
        value: https://*.onrender.com
