name: Test Application (Stable Version)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test application startup
      run: |
        timeout 10s uvicorn main:app --host 0.0.0.0 --port 8000 &
        sleep 5
        curl -f http://localhost:8000/ || exit 1
        echo "✅ Application startup test passed"

    - name: Test requirements
      run: |
        python -c "import fastapi, uvicorn, jinja2; print('✅ All required packages imported successfully')"

    - name: ✅ Deployment Note
      run: |
        echo "✅ Application tested successfully!"
        echo "📝 For deployment, use:"
        echo "   • Render: One-click deploy button in README"
        echo "   • Fly.io: CLI deployment (see DEPLOYMENT.md)"
        echo "   • Docker: Available for VPS deployment"
        echo "🚫 No automatic deployment to avoid platform conflicts"
